### ISSUE TITLE
Build failed on posix platform with NNI_GCC_VERSION >= 40700 while calling nni_atomic_cas() and nng_atomic_swap()

### ISSUE THREAD

**Issue by alvin1221** [nanomq/NanoNNG#135]
**Describe the bug**
Build failed on linux with gcc version = 4.8.5 while calling functions calling `nni_atomic_cas()` and `nng_atomic_swap()`.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NanoMQ version : 1.6.0-pre
 - Operating system and version : centos 7.4 &  Alibaba Cloud Linux 2
 - Compiler and language used: cmake, Ninja, C , gcc-4.8.5
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
related to upstream https://github.com/nanomsg/nng/issues/1586
