### ISSUE TITLE
QUIC bridging blocks NNG thread

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/NanoNNG#263]
**Describe the bug**
start nanomq in offline mode with quic bridging enabled
Then broker hangs forever

**Expected behavior**
broker start successfully and reconnects when network is restored

**Actual Behavior**
It hangs....

**To Reproduce**
start nanomq in offline mode with quic bridging enabled

** Environment Details **
 - NanoMQ version 0.11

**Client SDK**
not related 

**Additional context**
it awaits connect msg being sent

**Comment by wanghaEMQ** [comment]
Which has been fixed in the last master branch
