### ISSUE TITLE
Disconnect callback in the bridge is not called when tcp connection was closed.

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/NanoNNG#289]
**Describe the bug**
Disconnect callback in the bridge is not called when tcp connection was closed.

**Expected behavior**
Disconnect callback in bridge should be called when tcp connection was close.

**Actual Behavior**
No callback was called.

**To Reproduce**
Closing WIFI when log shows that TCP bridge connection has be connected.

** Environment Details **
 - NanoMQ version - latest
 - Operating system and version - OSX
 - Compiler and language used - Clang
 - testing scenario -

**Client SDK**
-

**Additional context**
-

**Comment by JaylinYu** [comment]
fixed nanosdk
